version: "3.9"
services:
  webapp:
    image: steebchen/nginx-spa:stable
    ports:
      - "10002:80"
    volumes:
      - type: bind
        source: ./webapp_react/build
        target: /app
        #target: /usr/share/nginx/html

